[project]
name = "geass"
version = "0.1.0"
readme = "README.md"
description = "Command your transcription API with Geass"
authors = [
    { name = "Tony Kabilan Okeke", email = "tonykabilanokeke@gmail.com" } 
]
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.18.1",
    "matplotlib>=3.9.2",
    "pillow>=10.4.0",
    "ffmpeg-python==0.2.0",
    "httpx==0.27.0",
    "pydantic==2.6.4",
    "pydantic-settings==2.2.1",
    "rich==13.7.1",
    "tqdm==4.66.2",
    "typer==0.9.0",
    "loguru==0.7.2",
    "html2text==2024.2.26",
    "transformers==4.36.2",
    "torch==2.3.1",
    "huggingface-hub==0.23.5",
]

[project.scripts]
geass = "geass.cli.main:app"

[project.urls]
Homepage = "https://github.com/Kabilan108/geass"

[tool.setuptools.packages.find]
where = ["."]
include = ["geass"]
exclude = ["geass/service"]

[tool.uv]
dev-dependencies = [
    "jupyter>=1.1.1",
    "modal==0.63.67",
]
package = true

