[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "geass"
version = "0.1.0"
description = "Command your audio transcriptions API with Geass"
authors = ["Kabilan108 <tonykabilanokeke@gmail.com>"]
packages = [
    { include = "geass", from = "." },
]
exclude = ["geass/service"]

[tool.poetry.dependencies]
python = "^3.10"
ffmpeg-python = "0.2.0"
httpx = "0.27.0"
pydantic = "2.6.4"
pydantic-settings = "2.2.1"
rich = "13.7.1"
tqdm = "4.66.2"
typer = "0.9.0"
loguru = "^0.7.2"

[tool.poetry.scripts]
geass = "geass.cli.main:app"

[tool.poetry.group.dev.dependencies]
modal = "0.61.58"
